### PR TITLE
fix(cms): navigation links in category navigation

### LINKED ISSUE #790: [BUG]Navigation block is not working
### Describe the bug
The side navigation is not working; after clicking on the subcategory the 404 error page appears. The same subcategory is available from megamenu.

###Steps to reproduce the behavior:

1. Go to the category 'Accessories'
2. Click on the subcategory 'Movies' 'See Movies' form the side menu
3. See the error
4. Click on subcategory 'Movies' from the MegaMenu

### Additional context
* subcategory 'Movies' 'See Movies' form the side menu
Accesiories
* subcategory 'Movies' from the MegaMenu
Accesories1

### PR DESCRIPTION
**Pull request by patzick**
## Changes

closes #790 

### Checklist

- [x] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

File: packages/default-theme/cms/elements/CmsElementCategoryNavigation.vue [hunk 1]
```diff
@@ -107,7 +110,7 @@ export default {
   },
   methods: {
     getCategoryUrl(route) {
-      return route.path || ''
```
Comment (mkucmus) [inline packages/default-theme/cms/elements/CmsElementCategoryNavigation.vue:110]: you can use `  { getCategoryUrl } from '@shopware-pwa/helpers'` like it was in packages/default-theme/components/SwTopNavigation.vue

**Comment by akrajna** [comment]
Works great :-)

File: packages/default-theme/cms/elements/CmsElementCategoryNavigation.vue (hunk 1 above)
Comment (patzick) [reply packages/default-theme/cms/elements/CmsElementCategoryNavigation.vue:110]: 👌 good point, fixed
