### PR TITLE
fix(theme): add products to carousels in product details

### LINKED ISSUE #344: Add Carousel with products fetch from api

### PR DESCRIPTION
**Pull request by krskibin**
closes #344

### CODE REVIEW

File: packages/default-theme/components/SwProductCarousel.vue [hunk 1]
```diff
@@ -33,65 +26,21 @@ export default {
...
+        pagination: {
+          page: 1,
+          limit: 10
         }
-      ]
+      }
     }
+  },
+  async mounted() {
+    this.products = await getProducts(this.searchCriteria)
```
Comment (patzick) [inline packages/default-theme/components/SwProductCarousel.vue]: why do you need to have searchCriteria inside `data`?  They are not going to change :)
Also please consult with @mkucmus searchQuery details to avoid this:
image

File: packages/default-theme/components/cms/elements/SwProductSlider.vue [hunk 2]
```diff
@@ -28,14 +29,15 @@ export default {
...
   computed: {
     products() {
-      return this.content && this.content.data
-        ? this.content.data.products
-        : [];
+      return this.content && this.content.data ? this.content.data.products : []
     },
     title() {
-      return this.content && this.content.config.title.value
+      console.log(this.content);
```
Comment (patzick) [inline packages/default-theme/components/cms/elements/SwProductSlider.vue]:
```suggestion
```
