### PR TITLE
fix: fix colors filters displaying

### LINKED ISSUE #647: [BUG] Bad color filter displaying
### Describe the bug

Color filter should be displayed in one line

- Open filters
- Go to colors
- See bug

### Additional context
image

### PR DESCRIPTION
**Pull request by Michal-Dziedzinski**
## Changes

closes #647 

before: 
image

after:
image

### Checklist

- [x] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

File: packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue [hunk 1]
```diff
@@ -69,7 +69,7 @@
         <div class="filters">
           <div v-for="filter in filters" :key="filter.name">
             <SfHeading class="filters__title" :level="4" :title="filter.name" />
-            <div v-if="filter && filter.options && filter.options.length">
+            <div v-if="filter && filter.options && filter.options.length" :class="{'filters__filter--color': filter && filter.name && filter.name === 'color'}">
```
Comment (patzick) [inline packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue:72]: v-if checks if filter is not null, so we can safely make it shorter :)
```suggestion
            <div v-if="filter && filter.options && filter.options.length" :class="{'filters__filter--color': filter.name === 'color'}">
```

Comment (Michal-Dziedzinski) [reply packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue]: Sure!
