### PR TITLE
fix: dropdown user icon

### LINKED ISSUE #769: [BUG] SfDropdown to userIcon to polish
### Describe the bug

**On demo instance:**
* after log out the dropdown does not disappear if user clicks outside the dropdown. The dropdown should disappear after clicking outside. 
Logout1

* dropdown should be centrally under the 'My account' icon as shown below:
dropdownCanary
Now it look as below:
dropdownDemo

* on mobile devices after pressing log out the dropdown disappears and appears for a moment to disappear again, as shown below:
Logout2
the dropdown should just disappears

**On demo and canary instance:** 

* on mobile devices, logout button in the popup should be centered
LogoutMobile

**On canary instance:**
* on mobile view for not logged in user after pressing the 'My account' icon nothing happens, as below:
MyAccountCanary

Expected behavior: for not logged in user after pressing the 'My account' icon   the login window should appears. 

### Steps to reproduce:
Initial conditions: user is logged in
1. Go to homepage
2. Click on 'My account' icon

### PR DESCRIPTION
**Pull request by pspaczek**
## Changes

closes #769

- [x] clicking outside 
- [x] center dropdown 
Zrzut ekranu 2020-05-27 o 14 10 17
- [x] click logout on mobile work
- [x] logout button styles
Zrzut ekranu 2020-05-27 o 14 18 24
- [x] open log in modal on mobile
### Checklist

- [ ] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

File: packages/default-theme/components/SwBottomNavigation.vue [hunk 1]
```diff
@@ -34,20 +34,20 @@
...
             <!-- TODO: change .native to @click after https://github.com/DivanteLtd/storefront-ui/issues/1097 -->
-            <SfSelectOption :value="getPageAccount" @click.native="goToMyAccount">
-                My account
+            <SfSelectOption
+              :value="getPageAccount"
+              @click.native="goToMyAccount"
+            >
+              My account
             </SfSelectOption>
             <!-- TODO: change .native to @click after https://github.com/DivanteLtd/storefront-ui/issues/1097 -->
```
Comment (patzick) [inline packages/default-theme/components/SwBottomNavigation.vue:46]: if works without native we should remove this TODO :)

Comment (pspaczek) [reply packages/default-theme/components/SwBottomNavigation.vue:46]: it didn't work :(
